import { Car } from '@/types';

export const CARS: Car[] = [
  {
    id: 'corolla',
    name: 'Toyota Corolla',
    type: 'hatchback',
    power: 139,
    transmission: 'Automatic',
    drive: 'FWD',
    mpg: 32,
    pricePerDay: 53,
    image: '/cars/store-car.png',
    year: 2023,
    make: 'toyota',
    model: 'corolla',
    cylinders: 4,
    displacement: 2.0,
    fuelType: 'gas',
    class: 'compact',
    images: ['/cars/store-car.png', '/cars/head-view.png', '/cars/store-car.png'],
  },
  {
    id: 'civic',
    name: 'Honda Civic',
    type: 'coupe',
    power: 158,
    transmission: 'Manual',
    drive: 'FWD',
    mpg: 30,
    pricePerDay: 53,
    image: '/cars/store-car.png',
    year: 2023,
    make: 'honda',
    model: 'civic',
    cylinders: 4,
    displacement: 1.5,
    fuelType: 'gas',
    class: 'compact',
    images: ['/cars/store-car.png', '/cars/head-view.png', '/cars/store-car.png'],
  },
  {
    id: 'tiguan',
    name: 'Volkswagen Tiguan',
    type: 'suv',
    power: 184,
    transmission: 'Automatic',
    drive: 'AWD',
    mpg: 27,
    pricePerDay: 67,
    image: '/cars/store-car.png',
    year: 2023,
    make: 'volkswagen',
    model: 'tiguan',
    cylinders: 4,
    displacement: 2.0,
    fuelType: 'gas',
    class: 'suv',
    images: ['/cars/store-car.png', '/cars/head-view.png', '/cars/store-car.png'],
  },
  {
    id: 'mazda6',
    name: 'Mazda6',
    type: 'wagon',
    power: 200,
    transmission: 'Manual',
    drive: 'RWD',
    mpg: 50,
    pricePerDay: 99,
    image: '/cars/store-car.png',
    year: 2023,
    make: 'mazda',
    model: 'mazda6',
    cylinders: 4,
    displacement: 2.5,
    fuelType: 'gas',
    class: 'wagon',
    images: ['/cars/store-car.png', '/cars/head-view.png', '/cars/store-car.png'],
  },
  {
    id: 'camry',
    name: 'Toyota Camry',
    type: 'sedan',
    power: 203,
    transmission: 'Automatic',
    drive: 'FWD',
    mpg: 28,
    pricePerDay: 65,
    image: '/cars/store-car.png',
    year: 2023,
    make: 'toyota',
    model: 'camry',
    cylinders: 4,
    displacement: 2.5,
    fuelType: 'gas',
    class: 'sedan',
    images: ['/cars/store-car.png', '/cars/head-view.png', '/cars/store-car.png'],
  },
  {
    id: 'accord',
    name: 'Honda Accord',
    type: 'crossover',
    power: 192,
    transmission: 'Automatic',
    drive: 'FWD',
    mpg: 30,
    pricePerDay: 62,
    image: '/cars/store-car.png',
    year: 2023,
    make: 'honda',
    model: 'accord',
    cylinders: 4,
    displacement: 1.5,
    fuelType: 'gas',
    class: 'crossover',
    images: ['/cars/store-car.png', '/cars/head-view.png', '/cars/store-car.png'],
  },
  {
    id: 'bmw3',
    name: 'BMW 3 Series',
    type: 'convertible',
    power: 255,
    transmission: 'Automatic',
    drive: 'RWD',
    mpg: 26,
    pricePerDay: 89,
    image: '/cars/store-car.png',
    year: 2023,
    make: 'bmw',
    model: '3-series',
    cylinders: 4,
    displacement: 2.0,
    fuelType: 'gas',
    class: 'luxury',
    images: ['/cars/store-car.png', '/cars/head-view.png', '/cars/store-car.png'],
  },
  {
    id: 'mercedes-c',
    name: 'Mercedes C-Class',
    type: 'pickup',
    power: 255,
    transmission: 'Automatic',
    drive: 'RWD',
    mpg: 25,
    pricePerDay: 95,
    image: '/cars/store-car.png',
    year: 2023,
    make: 'mercedes',
    model: 'c-class',
    cylinders: 4,
    displacement: 2.0,
    fuelType: 'gas',
    class: 'pickup',
    images: ['/cars/store-car.png', '/cars/head-view.png', '/cars/store-car.png'],
  },
  {
    id: 'audi-a4',
    name: 'Audi A4',
    type: 'van',
    power: 201,
    transmission: 'Automatic',
    drive: 'AWD',
    mpg: 27,
    pricePerDay: 78,
    image: '/cars/store-car.png',
    year: 2023,
    make: 'audi',
    model: 'a4',
    cylinders: 4,
    displacement: 2.0,
    fuelType: 'gas',
    class: 'van',
    images: ['/cars/store-car.png', '/cars/head-view.png', '/cars/store-car.png'],
  },
  {
    id: 'lexus-es',
    name: 'Lexus ES',
    type: 'electric',
    power: 203,
    transmission: 'Automatic',
    drive: 'FWD',
    mpg: 25,
    pricePerDay: 72,
    image: '/cars/store-car.png',
    year: 2023,
    make: 'lexus',
    model: 'es',
    cylinders: 4,
    displacement: 2.5,
    fuelType: 'electric',
    class: 'electric',
    images: ['/cars/store-car.png', '/cars/head-view.png', '/cars/store-car.png'],
  },
  {
    id: 'volkswagen-jetta',
    name: 'Volkswagen Jetta',
    type: 'sedan',
    power: 147,
    transmission: 'Automatic',
    drive: 'FWD',
    mpg: 31,
    pricePerDay: 48,
    image: '/cars/store-car.png',
    year: 2023,
    make: 'volkswagen',
    model: 'jetta',
    cylinders: 4,
    displacement: 1.4,
    fuelType: 'gas',
    class: 'compact',
    images: ['/cars/store-car.png', '/cars/head-view.png', '/cars/store-car.png'],
  },
  {
    id: 'nissan-altima',
    name: 'Nissan Altima',
    type: 'sedan',
    power: 188,
    transmission: 'Automatic',
    drive: 'FWD',
    mpg: 28,
    pricePerDay: 58,
    image: '/cars/store-car.png',
    year: 2023,
    make: 'nissan',
    model: 'altima',
    cylinders: 4,
    displacement: 2.5,
    fuelType: 'gas',
    class: 'sedan',
    images: ['/cars/store-car.png', '/cars/head-view.png', '/cars/store-car.png'],
  },
];
